# Đây là một tệp tin văn bản thuần túy (.txt hoặc .properties). Nó không phải là code, nó chỉ chứa các tham số thiết lập.
# Mục đích: Để có thể thay đổi cài đặt của Game mà không cần biên dịch (re-compile) lại code Java.
# VD: nội dung chứa gồm
# board.size=100
# game.time=120
# max.players=3
# db.url=jdbc:mysql://localhost:3306/game_db